# Generated by Django 2.2.3 on 2019-08-08 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='QQ',
            field=models.IntegerField(default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='mobile',
            field=models.IntegerField(default=0, max_length=11),
        ),
    ]
