# Generated by Django 2.2.3 on 2019-08-08 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20190808_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='QQ',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='mobile',
            field=models.CharField(max_length=11),
        ),
    ]
