# Generated by Django 2.2.3 on 2019-08-14 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20190812_1738'),
        ('account', '0005_auto_20190812_0908'),
    ]

    operations = [
    ]
