# Generated by Django 2.2.3 on 2019-08-14 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_merge_20190814_2113'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='username',
            new_name='user',
        ),
    ]
