# Generated by Django 2.2.1 on 2019-07-20 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190717_0042'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='auithor',
            new_name='author',
        ),
    ]
