# Generated by Django 2.2.1 on 2019-07-22 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190720_1950'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='see',
            field=models.IntegerField(default=0),
        ),
    ]
