# Generated by Django 2.2.3 on 2019-07-30 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_remove_blog_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='introduce',
            field=models.CharField(default='blank', max_length=200),
        ),
    ]
